name: gradle-ci
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
          cache: "gradle"
      - name: build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: "shadowJar"
      - name: upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          path: build/libs/*.jar